Full edition -layout
Alazar721/portifolio-mobile-version pull request #2
Opened 2022-12-09 18:42 UTC by Alazar721

- added full-version of my project layout
- used gird and flex to layout my project

2022-12-09 19:38 UTC, Gambit142 requested changes
Hi @Alazar721 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- README.md is professional ✔️ 
- Pull Request title is descriptive ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-09 19:38 UTC, Gambit142 commented on index.html
> +    <div class="recent-works">
- [ ] Kindly make this a `section` tag instead of a `div` tag. It is more semantic to use a `section` tag for standalone sections on a webpage. 👍

2022-12-09 19:38 UTC, Gambit142 commented on index.html
> +        <h1 class="head-title">My Recent Works</h1>
- [ ] Kindly change this `h1` tag to any of the `hx (h2-h6)` tags. It is the convention and best practice to use only one `h1` tag on a webpage. Kindly change it 👍

2022-12-09 19:38 UTC, Gambit142 commented on index.html
> +            <p class="title-post">Multi-Post Stories</p>
- [ ] Kindly change this `p` tag to any of the `hx (h2-h6)` tags. It is semantic to use `hx` tags for headings. Kindly change it 👍

2022-12-09 19:38 UTC, Gambit142 commented on styles.css
> +}
- [ ] One of the requirements for this project is to make your design identical to that of the Figma design you choose. The look of the button for each project card is different from that of the Figma template. Kindly make it identical.

### Your Design

![image](https://user-images.githubusercontent.com/77106962/206781565-ea363aab-6792-48cb-932e-60e95272acf0.png)

### Figma Template

![image](https://user-images.githubusercontent.com/77106962/206781646-bd813792-5f45-4883-94a6-567a529e9f79.png)

2022-12-09 19:38 UTC, Gambit142 commented on index.html
> +    <div class="about">
- [ ] Kindly make this a `section` tag instead of a `div` tag. It is more semantic to use a `section` tag for standalone sections on a webpage. 👍

2022-12-09 19:38 UTC, Gambit142 commented on index.html
> +      <h1 class="primery">About me</h1>
- [ ] Kindly change this `h1` tag to any of the `hx (h2-h6)` tags. It is the convention and best practice to use only one `h1` tag on a webpage. Kindly change it 👍

2022-12-10 06:12 UTC, amejid reviewed
Hi @Alazar721, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that linter checks are not running.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-10 07:24 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @Alazar721, 

I am Favour 👩🏽 , your reviewer for this PR.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)

## Highlights 💯 
- No Linter errors ✔️
- Good commit messages ✔️
- Professional Readme file ✔️
- Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 07:41 UTC, merged